"use client";
import { FormEvent, useState } from "react";
import { LockKeyhole } from "lucide-react";
import { Button } from "@/components/ui/button";
import { createClient } from "@/lib/supabase/client";

export default function LoginPage(){
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function authenticate(mode:"login"|"signup",event:FormEvent){event.preventDefault();setLoading(true);setError("");setMessage("");const supabase=createClient();const result=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(result.error){setError(result.error.message);setLoading(false);return}if(mode==="signup"&&!result.data.session){setMessage("Acesso criado. Confirme o e-mail enviado pelo Supabase antes de entrar.");setLoading(false);return}window.location.href="/"}
  return <main className="grid min-h-screen place-items-center px-5"><section className="w-full max-w-md rounded-3xl border border-[#30305c] bg-[#09092b] p-8 shadow-[0_25px_100px_#0009]"><span className="grid size-12 place-items-center rounded-2xl bg-[#ebf400] text-[#02021e]"><LockKeyhole/></span><p className="mt-8 text-[10px] font-semibold tracking-[.18em] text-[#85869b]">ÁREA PRIVADA</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Radar Local</h1><p className="mt-2 text-sm leading-6 text-[#9697aa]">Entre com seu e-mail e senha para acessar os dados protegidos no Supabase.</p><form className="mt-7 grid gap-4" onSubmit={event=>authenticate("login",event)}><label className="grid gap-2 text-xs text-[#b1b2c1]">E-mail<input autoFocus type="email" required value={email} onChange={event=>setEmail(event.target.value)} className="h-12 rounded-xl border border-[#34345f] bg-[#05051f] px-4 outline-none focus:border-[#8a8b4c]" placeholder="seu@email.com"/></label><label className="grid gap-2 text-xs text-[#b1b2c1]">Senha<input type="password" required minLength={8} value={password} onChange={event=>setPassword(event.target.value)} className="h-12 rounded-xl border border-[#34345f] bg-[#05051f] px-4 outline-none focus:border-[#8a8b4c]" placeholder="No mínimo 8 caracteres"/></label>{error&&<p role="alert" className="text-xs text-[#ff8f9a]">{error}</p>}{message&&<p className="text-xs leading-5 text-[#dce97a]">{message}</p>}<Button disabled={loading}>{loading?"Aguarde...":"Entrar no Radar"}</Button><Button type="button" variant="ghost" disabled={loading} onClick={event=>authenticate("signup",event)}>Criar meu acesso</Button></form></section></main>
}
