"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, AtSign, Building2, CalendarDays, Check, CheckCircle2, Clock3, ExternalLink, LayoutDashboard, LogOut, Mail, Map, MapPin, Menu, MessageCircle, Moon, Pencil, Phone, Plus, Search, Settings, Sun, Tag, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Company, CompanyStatus } from "./types";
import { addCompanyTask, deleteCompany, loadCompanies, saveCompany as persistCompany, setCompanyStatus, setContactMarker, toggleCompanyTask } from "./company-repository";
import { createClient } from "@/lib/supabase/client";

const commercialDefaults = { contacts:{whatsapp:false,phone:false,instagram:false,email:false}, projectValue:0, siteCreatedUrl:"", paymentStatus:"Pendente" as const, paymentDate:"", billingMonth:"", monthlyValue:0, monthlyPaid:false, monthlyPaymentDate:"", tasks:[] };
const nav = [
  ["Visão geral", LayoutDashboard], ["Fila de hoje", CalendarDays], ["Empresas", Building2], ["Aguardando", Clock3], ["Clientes fechados", CheckCircle2], ["Nichos", Tag], ["Cobertura", Map],
] as const;

function emptyCompany(): Company { return { ...commercialDefaults, contacts:{...commercialDefaults.contacts}, tasks:[], id:"", name:"", category:"", city:"", state:"", rating:0, reviews:0, phone:"", email:"", maps:"", website:"", instagram:"", status:"Novo", priority:"Média", notes:"", nextContact:"" }; }

export function Dashboard() {
  const [companies,setCompanies] = useState<Company[]>([]);
  const [ready,setReady] = useState(false);
  const [section,setSection] = useState("Fila de hoje");
  const [query,setQuery] = useState("");
  const [siteFilter,setSiteFilter] = useState("Todos");
  const [editing,setEditing] = useState<Company|null>(null);
  const [details,setDetails] = useState<Company|null>(null);
  const [mobileMenu,setMobileMenu] = useState(false);
  const [toast,setToast] = useState("");
  const [lightTheme,setLightTheme] = useState(false);
  const [dataError,setDataError] = useState("");

  const loadData=useCallback(async()=>{try{setDataError("");setCompanies(await loadCompanies())}catch(error){setDataError(error instanceof Error?error.message:"Não foi possível carregar os dados")}finally{setReady(true)}},[]);
  useEffect(() => {
    const timer=window.setTimeout(()=>{setLightTheme(window.localStorage.getItem("radar-theme")==="light");void loadData()},0);
    return()=>window.clearTimeout(timer);
  },[loadData]);
  useEffect(() => { if(ready) window.localStorage.setItem("radar-theme",lightTheme?"light":"dark"); },[lightTheme,ready]);

  const visible=useMemo(()=>companies.filter(company=>{
    if(section==="Fila de hoje"&&company.status!=="Fila de hoje")return false;
    if(section==="Aguardando"&&company.status!=="Aguardando")return false;
    if(section==="Clientes fechados"&&company.status!=="Cliente fechado")return false;
    if(siteFilter==="Com site"&&!company.website)return false;
    if(siteFilter==="Sem site"&&company.website)return false;
    const text=`${company.name} ${company.category} ${company.city}`.toLocaleLowerCase("pt-BR");
    return text.includes(query.toLocaleLowerCase("pt-BR").trim());
  }),[companies,query,section,siteFilter]);

  function notify(message:string){setToast(message);window.setTimeout(()=>setToast(""),2500)}
  function changeSection(value:string){setSection(value);setMobileMenu(false)}
  async function saveCompany(event:FormEvent<HTMLFormElement>){
    event.preventDefault(); if(!editing)return; try{await persistCompany(editing);setEditing(null);setSection("Empresas");await loadData();notify(editing.id?"Empresa atualizada":"Empresa cadastrada")}catch(error){notify(error instanceof Error?error.message:"Não foi possível salvar")}
  }
  async function updateStatus(id:string,status:CompanyStatus){try{await setCompanyStatus(id,status);setDetails(null);await loadData();notify(`Status alterado para ${status}`)}catch{notify("Não foi possível alterar o status")}}
  async function toggleContact(id:string,channel:keyof Company["contacts"]){const company=companies.find(item=>item.id===id);if(!company)return;try{await setContactMarker(id,channel,company.contacts[channel]);await loadData();notify("Marcador de contato atualizado")}catch{notify("Não foi possível atualizar o contato")}}
  async function removeCompany(id:string){if(!window.confirm("Excluir esta empresa definitivamente?"))return;try{await deleteCompany(id);setDetails(null);await loadData();notify("Empresa excluída")}catch{notify("Não foi possível excluir")}}
  async function createTask(companyId:string,title:string,dueDate:string){try{await addCompanyTask(companyId,title,dueDate);const items=await loadCompanies();setCompanies(items);const refreshed=items.find(item=>item.id===companyId);if(refreshed)setDetails(refreshed);notify("Tarefa adicionada")}catch{notify("Não foi possível adicionar a tarefa")}}
  async function toggleTask(companyId:string,task:Company["tasks"][number]){try{await toggleCompanyTask(task);const items=await loadCompanies();setCompanies(items);const refreshed=items.find(item=>item.id===companyId);if(refreshed)setDetails(refreshed)}catch{notify("Não foi possível atualizar a tarefa")}}

  return <div className={`${lightTheme?"theme-light":""} min-h-screen lg:grid lg:grid-cols-[260px_1fr]`}>
    <aside className={`${mobileMenu?"flex":"hidden"} app-sidebar fixed inset-0 z-40 flex-col border-r border-[#242449] bg-[#05051f] px-5 py-7 lg:sticky lg:top-0 lg:flex lg:h-screen`}>
      <div className="mb-9 flex items-center gap-3 px-2"><span className="grid size-10 place-items-center rounded-xl bg-[#ebf400] font-bold text-[#02021e]">R</span><div><strong className="block text-sm">Radar Local</strong><span className="text-[11px] text-[#8e8fa4]">Krake Digital</span></div><button className="ml-auto lg:hidden" onClick={()=>setMobileMenu(false)} aria-label="Fechar menu"><X/></button></div>
      <nav className="grid gap-1">{nav.map(([label,Icon])=><button key={label} onClick={()=>changeSection(label)} className={`sidebar-nav-item flex min-h-11 items-center gap-3 rounded-xl px-3 text-left text-sm transition ${section===label?"is-active bg-[#171746] text-white shadow-[inset_3px_0_#ebf400]":"text-[#999aac] hover:bg-[#101034] hover:text-white"}`}><Icon size={18}/><span>{label}</span>{label==="Fila de hoje"&&<b className="ml-auto rounded-full bg-[#ebf400] px-2 py-0.5 text-[10px] text-[#02021e]">{companies.filter(c=>c.status==="Fila de hoje").length}</b>}</button>)}</nav>
      <div className="mt-auto border-t border-[#242449] pt-5"><button className="flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-sm text-[#999aac]"><Settings size={18}/>Configurações</button><button onClick={async()=>{await createClient().auth.signOut();window.location.href="/login"}} className="mt-3 flex w-full items-center gap-3 rounded-xl bg-[#0d0d31] p-3 text-left"><span className="grid size-9 place-items-center rounded-full border border-[#3a3a61] text-xs font-semibold">GW</span><span className="min-w-0 flex-1"><strong className="block truncate text-xs">Gabriel</strong><span className="text-[10px] text-[#8e8fa4]">Dados no Supabase</span></span><LogOut size={15} className="text-[#77788d]"/></button></div>
    </aside>
    <main className="min-w-0">
      <header className="app-header sticky top-0 z-30 flex min-h-20 items-center gap-3 border-b border-[#242449] bg-[#02021ee8] px-4 backdrop-blur-xl md:px-8"><button onClick={()=>setMobileMenu(true)} className="lg:hidden" aria-label="Abrir menu"><Menu/></button><label className="relative max-w-xl flex-1"><Search className="absolute left-4 top-3.5 text-[#77788d]" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} className="input-ui h-12 w-full rounded-xl border border-[#292951] bg-[#0b0b2c] pl-11 pr-4 text-sm outline-none placeholder:text-[#66677c] focus:border-[#7b7c48]" placeholder="Buscar empresa, nicho ou cidade..."/></label><button onClick={()=>setLightTheme(value=>!value)} className="grid size-11 place-items-center rounded-xl border border-[#30305c] bg-[#0b0b2c]" aria-label={lightTheme?"Usar tema escuro":"Usar tema claro"}>{lightTheme?<Moon size={18}/>:<Sun size={18}/>}</button><Button onClick={()=>setEditing(emptyCompany())}><Plus size={17}/><span className="hidden sm:inline">Nova empresa</span></Button></header>
      <div className="mx-auto max-w-7xl px-4 py-9 md:px-8 md:py-12">
        <section className="mb-9 flex flex-col gap-7 xl:flex-row xl:items-end xl:justify-between"><div><p className="section-eyebrow mb-3 text-[10px] font-semibold tracking-[.18em] text-[#7f8095]">RADAR LOCAL · PROSPECÇÃO</p><h1 className="text-3xl font-semibold tracking-[-.04em] md:text-4xl">{section}</h1><p className="section-description mt-2 text-sm text-[#999aac]">{section==="Fila de hoje"?"Abra o contato e leve a conversa com o texto pronto.":"Organize e acompanhe as empresas que você pesquisou."}</p></div><div className="stats-ui grid grid-cols-3 overflow-hidden rounded-2xl border border-[#292951] bg-[#090929]"><Stat value={companies.length} label="Empresas"/><Stat value={companies.filter(c=>c.status==="Aguardando").length} label="Aguardando"/><Stat value={companies.filter(c=>!c.website).length} label="Sem site" last/></div></section>
        <div className="mb-4 flex items-center justify-between"><span className="results-label text-[10px] font-semibold tracking-[.17em] text-[#818297]"><b className="results-count text-white">{visible.length}</b> RESULTADOS</span><select value={siteFilter} onChange={e=>setSiteFilter(e.target.value)} className="h-10 rounded-xl border border-[#292951] bg-[#0b0b2c] px-3 text-xs outline-none"><option>Todos</option><option>Com site</option><option>Sem site</option></select></div>
        {dataError&&<div className="mb-4 rounded-xl border border-[#71383d] bg-[#31171a] px-4 py-3 text-xs text-[#ffadb4]">{dataError}</div>}{!ready&&<div className="py-20 text-center text-sm text-[#8f90a5]">Carregando dados protegidos...</div>}<section className="grid gap-3">{visible.map((company,index)=>{
          const openTasks=company.tasks.filter(task=>!task.done);
          return <article key={company.id} className="company-card-ui animate-card grid gap-5 rounded-2xl border border-[#292951] bg-gradient-to-br from-[#101036] to-[#090927] p-5 transition hover:border-[#444475] md:grid-cols-[1fr_auto] md:p-6" style={{animationDelay:`${index*45}ms`}}>
            {openTasks.length>0&&<button onClick={()=>setDetails(company)} className="task-alert -m-2 mb-0 flex items-center gap-2 rounded-xl border border-[#685e24] bg-[#332d12] px-3 py-2 text-left text-xs text-[#fff18a] md:col-span-2"><AlertCircle size={15}/><strong>{openTasks.length} {openTasks.length===1?"tarefa pendente":"tarefas pendentes"}</strong><span className="ml-auto text-[10px]">Ver tarefas</span></button>}
            <button className="flex min-w-0 items-start gap-4 text-left" onClick={()=>setDetails(company)}><span className="company-avatar hidden size-12 shrink-0 place-items-center rounded-xl border border-[#353562] bg-[#171744] text-xs font-semibold text-[#ebf400] sm:grid">{company.name.split(" ").slice(0,2).map(n=>n[0]).join("")}</span><span className="min-w-0"><strong className="block truncate text-base md:text-lg">{company.name}</strong><span className="mt-2 flex flex-wrap items-center gap-2 text-[10px]"><b className={`company-chip rounded-full border px-2 py-1 font-medium ${company.website?"has-site border-[#53622e] text-[#dce86f]":"border-[#484858] text-[#aaaabd]"}`}>{company.website?"● com site":"○ sem site"}</b><b className="company-chip rounded-full border border-[#34345d] px-2 py-1 font-medium text-[#b0b1c2]">{company.category}</b><b className="company-chip rounded-full border border-[#34345d] px-2 py-1 font-medium text-[#b0b1c2]">{company.status}</b><em className="company-location not-italic text-[#848599]">{company.city}, {company.state}</em></span></span></button>
            <div className="text-left md:text-right"><strong className="rating-ui text-sm text-[#f3dd75]">★ {company.rating.toFixed(1)}</strong><span className="review-count-ui ml-2 text-[10px] text-[#7f8094] md:ml-0 md:block">{company.reviews.toLocaleString("pt-BR")} avaliações</span></div>
            <div className="contact-markers md:col-span-2"><span>Contato realizado:</span><ContactMarker active={company.contacts.whatsapp} label="WhatsApp" icon={<MessageCircle size={13}/>} onClick={()=>toggleContact(company.id,"whatsapp")}/><ContactMarker active={company.contacts.phone} label="Ligação" icon={<Phone size={13}/>} onClick={()=>toggleContact(company.id,"phone")}/><ContactMarker active={company.contacts.instagram} label="Instagram" icon={<AtSign size={13}/>} onClick={()=>toggleContact(company.id,"instagram")}/><ContactMarker active={company.contacts.email} label="E-mail" icon={<Mail size={13}/>} onClick={()=>toggleContact(company.id,"email")}/></div>
            {company.status==="Cliente fechado"&&<div className="client-summary md:col-span-2"><strong>Cliente fechado</strong><span>Projeto: {company.projectValue.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</span><span className={company.monthlyPaid?"paid":"pending"}>{company.monthlyPaid?`Mensalidade paga${company.monthlyPaymentDate?` em ${new Date(`${company.monthlyPaymentDate}T12:00`).toLocaleDateString("pt-BR")}`:""}`:"Mensalidade pendente"}</span></div>}
            <div className="grid gap-2 md:col-span-2 md:grid-cols-[minmax(240px,1.8fr)_auto_auto_auto]"><a href={`https://wa.me/${company.phone}`} target="_blank" className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white text-xs font-semibold text-[#02021e]"><MessageCircle size={16}/>Abrir WhatsApp<ExternalLink size={13}/></a><a href={company.maps} target="_blank" className="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#30305c] px-4 text-xs text-[#b0b1c2]"><MapPin size={15}/>Maps</a><Button variant="secondary" onClick={()=>setEditing(company)}><Pencil size={15}/>Editar</Button><Button variant="ghost" onClick={()=>updateStatus(company.id,"Descartado")}><Trash2 size={14}/>Descartar</Button></div>
          </article>})}{visible.length===0&&<div className="rounded-2xl border border-dashed border-[#34345f] py-20 text-center"><Search className="mx-auto text-[#66677b]"/><h2 className="mt-4 font-semibold">Nenhuma empresa encontrada</h2><p className="mt-1 text-xs text-[#898a9f]">Ajuste os filtros ou adicione uma nova empresa.</p></div>}</section>
      </div>
    </main>
    {editing&&<CompanyModal company={editing} onChange={setEditing} onClose={()=>setEditing(null)} onSubmit={saveCompany}/>} {details&&<DetailsDrawer company={details} onClose={()=>setDetails(null)} onEdit={()=>{setEditing(details);setDetails(null)}} onStatus={updateStatus} onAddTask={createTask} onToggleTask={toggleTask} onDelete={removeCompany}/>} {toast&&<div className="fixed bottom-6 left-1/2 z-[80] -translate-x-1/2 rounded-xl border border-[#687132] bg-[#272a16] px-5 py-3 text-xs text-[#ecf98a] shadow-2xl">✓ {toast}</div>}
  </div>
}

function Stat({value,label,last=false}:{value:number;label:string;last?:boolean}){return <div className={`min-w-24 px-5 py-4 ${last?"":"border-r border-[#292951]"}`}><strong className="block text-lg">{value}</strong><span className="text-[10px] text-[#898a9f]">{label}</span></div>}

function ContactMarker({active,label,icon,onClick}:{active:boolean;label:string;icon:React.ReactNode;onClick:()=>void}){return <button type="button" onClick={onClick} className={active?"active":""}>{icon}{label}{active&&<Check size={12}/>}</button>}

function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`grid gap-2 text-[11px] text-[#b3b4c4] ${wide?"sm:col-span-2":""}`}>{label}{children}</label>}
const inputClass="h-11 w-full rounded-xl border border-[#30305c] bg-[#080824] px-3 text-sm text-white outline-none placeholder:text-[#5f6074] focus:border-[#81824a]";

function CompanyModal({company,onChange,onClose,onSubmit}:{company:Company;onChange:(value:Company)=>void;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){
  const set=<K extends keyof Company>(key:K,value:Company[K])=>onChange({...company,[key]:value});
  return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/75 p-4 backdrop-blur-sm" onMouseDown={onClose}><section className="modal-panel my-6 w-full max-w-3xl rounded-3xl border border-[#3a3a65] bg-[#0a0a2b] shadow-2xl" onMouseDown={e=>e.stopPropagation()}><header className="flex items-start justify-between border-b border-[#292951] p-6"><div><p className="text-[10px] font-semibold tracking-[.16em] text-[#85869b]">{company.id?"EDITAR REGISTRO":"NOVO REGISTRO"}</p><h2 className="mt-2 text-2xl font-semibold">{company.id?"Editar empresa":"Adicionar empresa"}</h2><p className="mt-1 text-xs text-[#8e8fa4]">Dados da empresa, negociação e cobrança no mesmo lugar.</p></div><button onClick={onClose} aria-label="Fechar"><X/></button></header><form onSubmit={onSubmit} className="p-6">
    <h3 className="form-section-title">Empresa e contato</h3><div className="grid gap-4 sm:grid-cols-2">
      <Field label="Nome da empresa" wide><input className={`${inputClass} input-ui`} required value={company.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="Categoria"><input className={`${inputClass} input-ui`} required value={company.category} onChange={e=>set("category",e.target.value)}/></Field><Field label="Cidade"><input className={`${inputClass} input-ui`} required value={company.city} onChange={e=>set("city",e.target.value)}/></Field><Field label="Estado"><input className={`${inputClass} input-ui`} maxLength={2} value={company.state} onChange={e=>set("state",e.target.value.toUpperCase())}/></Field><Field label="WhatsApp"><input className={`${inputClass} input-ui`} value={company.phone} onChange={e=>set("phone",e.target.value)}/></Field><Field label="E-mail"><input className={`${inputClass} input-ui`} type="email" value={company.email} onChange={e=>set("email",e.target.value)}/></Field><Field label="Instagram"><input className={`${inputClass} input-ui`} value={company.instagram} onChange={e=>set("instagram",e.target.value)}/></Field><Field label="Site atual"><input className={`${inputClass} input-ui`} type="url" value={company.website} onChange={e=>set("website",e.target.value)}/></Field><Field label="Google Maps" wide><input className={`${inputClass} input-ui`} type="url" value={company.maps} onChange={e=>set("maps",e.target.value)}/></Field><Field label="Nota no Google"><input className={`${inputClass} input-ui`} type="number" min="0" max="5" step="0.1" value={company.rating} onChange={e=>set("rating",Number(e.target.value))}/></Field><Field label="Número de avaliações"><input className={`${inputClass} input-ui`} type="number" min="0" value={company.reviews} onChange={e=>set("reviews",Number(e.target.value))}/></Field>
    </div>
    <h3 className="form-section-title mt-8">Negociação</h3><div className="grid gap-4 sm:grid-cols-2"><Field label="Status"><select className={`${inputClass} input-ui`} value={company.status} onChange={e=>set("status",e.target.value as CompanyStatus)}><option>Novo</option><option>Fila de hoje</option><option>Aguardando</option><option>Respondeu</option><option>Oferta recusada</option><option>Cliente fechado</option><option>Descartado</option></select></Field><Field label="Prioridade"><select className={`${inputClass} input-ui`} value={company.priority} onChange={e=>set("priority",e.target.value as Company["priority"])}><option>Baixa</option><option>Média</option><option>Alta</option></select></Field><Field label="Próximo contato"><input className={`${inputClass} input-ui`} type="date" value={company.nextContact} onChange={e=>set("nextContact",e.target.value)}/></Field><Field label="Valor cobrado pelo site"><input className={`${inputClass} input-ui`} type="number" min="0" step="0.01" value={company.projectValue} onChange={e=>set("projectValue",Number(e.target.value))}/></Field><Field label="Pagamento do projeto"><select className={`${inputClass} input-ui`} value={company.paymentStatus} onChange={e=>set("paymentStatus",e.target.value as Company["paymentStatus"])}><option>Pendente</option><option>Parcial</option><option>Pago</option></select></Field><Field label="Data do pagamento"><input className={`${inputClass} input-ui`} type="date" value={company.paymentDate} onChange={e=>set("paymentDate",e.target.value)}/></Field><Field label="Link do site criado" wide><input className={`${inputClass} input-ui`} type="url" value={company.siteCreatedUrl} onChange={e=>set("siteCreatedUrl",e.target.value)}/></Field></div>
    <h3 className="form-section-title mt-8">Cobrança mensal</h3><div className="grid gap-4 sm:grid-cols-2"><Field label="Mês de referência"><input className={`${inputClass} input-ui`} type="month" value={company.billingMonth} onChange={e=>set("billingMonth",e.target.value)}/></Field><Field label="Valor mensal"><input className={`${inputClass} input-ui`} type="number" min="0" step="0.01" value={company.monthlyValue} onChange={e=>set("monthlyValue",Number(e.target.value))}/></Field><Field label="Pagamento do mês"><select className={`${inputClass} input-ui`} value={company.monthlyPaid?"Pago":"Pendente"} onChange={e=>set("monthlyPaid",e.target.value==="Pago")}><option>Pendente</option><option>Pago</option></select></Field><Field label="Data do pagamento mensal"><input className={`${inputClass} input-ui`} type="date" value={company.monthlyPaymentDate} onChange={e=>set("monthlyPaymentDate",e.target.value)}/></Field><Field label="Observações" wide><textarea className="input-ui min-h-24 rounded-xl border border-[#30305c] bg-[#080824] p-3 text-sm outline-none focus:border-[#81824a]" value={company.notes} onChange={e=>set("notes",e.target.value)}/></Field></div>
    <footer className="mt-6 flex justify-end gap-3"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit">{company.id?"Salvar alterações":"Cadastrar empresa"}</Button></footer>
  </form></section></div>
}

function DetailsDrawer({company,onClose,onEdit,onStatus,onAddTask,onToggleTask,onDelete}:{company:Company;onClose:()=>void;onEdit:()=>void;onStatus:(id:string,status:CompanyStatus)=>void;onAddTask:(companyId:string,title:string,dueDate:string)=>Promise<void>;onToggleTask:(companyId:string,task:Company["tasks"][number])=>Promise<void>;onDelete:(id:string)=>void}){
  const [taskTitle,setTaskTitle]=useState(""); const [taskDate,setTaskDate]=useState("");
  async function addTask(event:FormEvent){event.preventDefault();if(!taskTitle.trim())return;await onAddTask(company.id,taskTitle.trim(),taskDate);setTaskTitle("");setTaskDate("")}
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/70 backdrop-blur-sm" onMouseDown={onClose}><aside className="drawer-panel h-full w-full max-w-xl overflow-y-auto border-l border-[#3a3a65] bg-[#080828] p-7" onMouseDown={e=>e.stopPropagation()}><button className="float-right" onClick={onClose} aria-label="Fechar"><X/></button><div className="pt-12"><span className="grid size-16 place-items-center rounded-2xl border border-[#3a3a65] bg-[#151544] font-semibold text-[#ebf400]">{company.name.split(" ").slice(0,2).map(n=>n[0]).join("")}</span><p className="mt-7 text-[10px] font-semibold tracking-[.16em] text-[#85869b]">DETALHES DA EMPRESA</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em]">{company.name}</h2><p className="mt-2 text-sm text-[#9495a9]">{company.category} · {company.city}, {company.state}</p></div>
    <section className="tasks-panel mt-7 rounded-2xl border border-[#3b3b66] p-4"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold">Tarefas do cliente</h3><span className="text-[10px] text-[#9293a6]">{company.tasks.filter(task=>!task.done).length} pendentes</span></div><div className="grid gap-2">{company.tasks.map(task=><button key={task.id} onClick={()=>void onToggleTask(company.id,task)} className={`flex items-start gap-3 rounded-xl border p-3 text-left text-xs ${task.done?"border-[#31523c] bg-[#10271b] text-[#8fd6a3]":"border-[#4a472b] bg-[#282510] text-[#fff09a]"}`}><span className="mt-0.5 grid size-4 shrink-0 place-items-center rounded border">{task.done&&<Check size={11}/>}</span><span className={task.done?"line-through":""}>{task.title}{task.dueDate&&<small className="mt-1 block opacity-70">Prazo: {new Date(`${task.dueDate}T12:00`).toLocaleDateString("pt-BR")}</small>}</span></button>)}{company.tasks.length===0&&<p className="py-2 text-xs text-[#85869b]">Nenhuma tarefa cadastrada.</p>}</div><form onSubmit={addTask} className="mt-3 grid grid-cols-[1fr_auto] gap-2"><input className="input-ui h-10 rounded-xl border border-[#30305c] bg-[#080824] px-3 text-xs outline-none" value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="Nova tarefa..."/><input className="input-ui h-10 rounded-xl border border-[#30305c] bg-[#080824] px-2 text-xs outline-none" type="date" value={taskDate} onChange={e=>setTaskDate(e.target.value)}/><Button className="col-span-2 min-h-10" type="submit"><Plus size={14}/>Adicionar tarefa</Button></form></section>
    <div className="stats-ui mt-7 grid grid-cols-2 overflow-hidden rounded-2xl border border-[#30305c]"><Stat value={company.rating} label="Nota no Google"/><Stat value={company.reviews} label="Avaliações" last/></div>
    {company.status==="Cliente fechado"&&<section className="mt-7 rounded-2xl border border-[#3a4f31] bg-[#102318] p-4"><h3 className="text-sm font-semibold text-[#a9e68c]">Dados do cliente fechado</h3><dl className="mt-3 grid gap-3 text-xs"><div><dt className="text-[#77907b]">Valor do projeto</dt><dd>{company.projectValue.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})} · {company.paymentStatus}</dd></div><div><dt className="text-[#77907b]">Mensalidade</dt><dd>{company.monthlyValue.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})} · {company.monthlyPaid?"Paga":"Pendente"}{company.monthlyPaymentDate?` em ${new Date(`${company.monthlyPaymentDate}T12:00`).toLocaleDateString("pt-BR")}`:""}</dd></div>{company.siteCreatedUrl&&<a className="text-[#c9ef76] underline" href={company.siteCreatedUrl} target="_blank">Abrir site criado ↗</a>}</dl></section>}
    <dl className="mt-7 divide-y divide-[#292951]">{[["Status",company.status],["Prioridade",company.priority],["WhatsApp",company.phone||"Não informado"],["E-mail",company.email||"Não informado"],["Site atual",company.website||"Não possui site"],["Instagram",company.instagram||"Não informado"],["Próximo contato",company.nextContact||"Não agendado"],["Observações",company.notes||"Sem observações"]].map(([term,value])=><div key={term} className="py-4"><dt className="text-[10px] uppercase tracking-wider text-[#77788d]">{term}</dt><dd className="mt-1 break-words text-sm">{value}</dd></div>)}</dl><div className="mt-7 grid gap-2"><Button onClick={onEdit}><Pencil size={16}/>Editar todos os dados</Button><Button variant="secondary" onClick={()=>onStatus(company.id,"Cliente fechado")}><CheckCircle2 size={16}/>Marcar como cliente fechado</Button><Button variant="ghost" onClick={()=>onStatus(company.id,"Oferta recusada")}>Oferta recusada pelo cliente</Button><Button variant="ghost" onClick={()=>onDelete(company.id)}><Trash2 size={15}/>Excluir empresa</Button></div></aside></div>
}
